# Generated by Django 4.1.4 on 2023-02-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_crud_op', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Employee',
        ),
    ]
